version: "3.9"

networks:
  algafood-network:
    driver: bridge

services:
  algafood-postgres:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "algafood"
    ports:
      - "5432:5432"
    networks:
      - algafood-network

  algafood-redis:
    image: redis:6.2.1-alpine
    networks:
      - algafood-network

  algafood-api:
    image: algafood-api
    command: [ "/wait-for-it.sh", "algafood-postgres:5432", "-t", "30", "--", "java", "-jar", "api.jar" ]
    environment:
      DB_HOST: algafood-postgres
    networks:
      - algafood-network
    depends_on:
      - algafood-postgres

  algafood-proxy:
    build: ./nginx
    image: algafood-proxy
    ports:
      - "8080:80"
    networks:
      - algafood-network
    depends_on:
      - algafood-api